### ISSUE TITLE
Cannot find module '../build/Release/hash'

### ISSUE THREAD

**Issue by carpben** [sebastian-software/prepublish#40]
After running 'npm run prepare' I'm getting this error: 

    module.js:549
    throw err;
    ^

    Error: Cannot find module '../build/Release/hash'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\dev\react-projects\shared\gw-style- tools\node_modules\xxhash\lib\xxhash.js:4:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1

I just had a package.json, and a src folder with index.js, and then followed the readme file, and the Install section. I work on a Windows computer, with a PowerShell terminal. 
Have u seen this error before? Does the package run well on Windows? Can u suggest a remedy?

**Comment by swernerx** [comment]
Looks like something went wrong during installation. Can you verify that node-gyp is working correctly for you?
